get http://localhost:3000/todos/?status=TO%20DO

###

get http://localhost:3000/todos/

###

get http://localhost:3000/agenda/?date=2021-0-04 

###

post http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-10-22"
}

###
put http://localhost:3000/todos/4
Content-Type: application/json

{
 "todo": "Finalize event theme"
}

###
delete http://localhost:3000/todos/6